import {
  createHash,
  createHmac,
  timingSafeEqual,
} from "node:crypto";
import {
  defaultTreeAdapter,
  parse as parseHtml,
  serialize as serializeHtml,
  type DefaultTreeAdapterTypes,
} from "parse5";

export const PAGE_FILENAME = "thread-page.html";
export const MAX_PAGE_BYTES = 5 * 1024 * 1024;
export const VIEWER_TOKEN_TTL_MS = 2 * 60 * 60 * 1000;

export type PageTokenScope = "render" | "action";

export interface PageTokenPayload {
  v: 2;
  scope: PageTokenScope;
  threadId: string;
  pageHash: string;
  iat: number;
  exp: number;
}

export type FormAnswerValue = string | string[] | boolean;

export interface FormAnswer {
  name: string;
  label: string;
  value: FormAnswerValue;
}

export interface SubmissionFile {
  field: string;
  name: string;
  path: string;
  sizeBytes: number;
}

export interface Submission {
  actionToken: string;
  submissionId: string;
  pageHash: string;
  title: string;
  answers: FormAnswer[];
  files: SubmissionFile[];
}

/** Upload names are generated by the plugin, never trusted from the page. */
export const UPLOAD_DIRNAME = "thread-page-uploads";
export const MAX_UPLOAD_BYTES = 24 * 1024 * 1024;

export function safeUploadName(raw: string): string {
  let decoded = raw;
  try {
    decoded = decodeURIComponent(raw);
  } catch {
    decoded = raw;
  }
  const base = decoded.split(/[\\/]/).pop() ?? "upload";
  const cleaned = base.replace(/[^A-Za-z0-9._-]/g, "_").replace(/^\.+/, "");
  return cleaned.slice(0, 80) || "upload";
}

export function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

export function sha256Text(value: string): string {
  return createHash("sha256").update(value, "utf8").digest("hex");
}

export const CONFIRMATION_TTL_MS = 2 * 60 * 1000;

/**
 * A signed challenge for one confirmed capability call.
 *
 * The server mints it, the trusted outer shell shows its summary and mints
 * nothing itself, and the server re-checks the signature before acting. The
 * untrusted page never authors the summary and cannot forge or replay a
 * challenge: it is bound to one request id, method, parameter fingerprint,
 * page revision, and thread, and it expires quickly.
 */
export interface ConfirmationChallengePayload {
  v: 2;
  scope: "confirm";
  threadId: string;
  pageHash: string;
  requestId: string;
  method: string;
  paramsHash: string;
  summary: string;
  iat: number;
  exp: number;
}

export function signConfirmationChallenge(
  payload: ConfirmationChallengePayload,
  key: Uint8Array,
): string {
  const encoded = encodeJson(payload);
  const signature = createHmac("sha256", key)
    .update(encoded, "ascii")
    .digest("base64url");
  return `${encoded}.${signature}`;
}

function isConfirmationChallenge(
  value: unknown,
  now: number,
): value is ConfirmationChallengePayload {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const payload = value as Record<string, unknown>;
  return (
    payload.v === 2 &&
    payload.scope === "confirm" &&
    typeof payload.threadId === "string" &&
    /^[A-Za-z0-9_-]{3,128}$/.test(payload.threadId) &&
    typeof payload.pageHash === "string" &&
    /^[a-f0-9]{64}$/.test(payload.pageHash) &&
    typeof payload.requestId === "string" &&
    payload.requestId.length > 0 &&
    payload.requestId.length <= 96 &&
    typeof payload.method === "string" &&
    payload.method.length > 0 &&
    payload.method.length <= 96 &&
    typeof payload.paramsHash === "string" &&
    /^[a-f0-9]{64}$/.test(payload.paramsHash) &&
    typeof payload.summary === "string" &&
    payload.summary.length > 0 &&
    payload.summary.length <= 512 &&
    typeof payload.iat === "number" &&
    Number.isSafeInteger(payload.iat) &&
    typeof payload.exp === "number" &&
    Number.isSafeInteger(payload.exp) &&
    payload.iat <= now + 30_000 &&
    payload.exp > now &&
    payload.exp > payload.iat &&
    payload.exp - payload.iat <= CONFIRMATION_TTL_MS
  );
}

export function verifyConfirmationChallenge(
  token: string,
  key: Uint8Array,
  now = Date.now(),
): ConfirmationChallengePayload | null {
  const parts = token.split(".");
  if (parts.length !== 2 || !parts[0] || !parts[1]) return null;
  const [encoded, suppliedSignature] = parts;
  try {
    const expected = createHmac("sha256", key)
      .update(encoded, "ascii")
      .digest();
    const supplied = Buffer.from(suppliedSignature, "base64url");
    if (supplied.byteLength !== expected.byteLength) return null;
    if (supplied.toString("base64url") !== suppliedSignature) return null;
    if (!timingSafeEqual(supplied, expected)) return null;
    const decoded = JSON.parse(
      Buffer.from(encoded, "base64url").toString("utf8"),
    ) as unknown;
    return isConfirmationChallenge(decoded, now) ? decoded : null;
  } catch {
    return null;
  }
}

export function etagForHash(hash: string): string {
  return `"${hash}"`;
}

export function makeSeedFragment(title: string): string {
  return `<header>
  <h1>${escapeHtml(title)}</h1>
  <p>This page belongs to this bb thread.</p>
</header>
<main>
  <p>Edit this file directly to keep the page current.</p>
  <form data-title="${escapeHtml(title)}">
    <label>Reply
      <textarea name="reply" rows="4" placeholder="Write a response"></textarea>
    </label>
    <button name="action" value="Reply">Reply</button>
  </form>
</main>
`;
}

function encodeJson(value: unknown): string {
  return Buffer.from(JSON.stringify(value), "utf8").toString("base64url");
}

export function signPageToken(
  payload: PageTokenPayload,
  key: Uint8Array,
): string {
  const encoded = encodeJson(payload);
  const signature = createHmac("sha256", key)
    .update(encoded, "ascii")
    .digest("base64url");
  return `${encoded}.${signature}`;
}

function isPageTokenPayload(
  value: unknown,
  expectedScope: PageTokenScope,
  now: number,
): value is PageTokenPayload {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const payload = value as Record<string, unknown>;
  return (
    payload.v === 2 &&
    payload.scope === expectedScope &&
    typeof payload.threadId === "string" &&
    /^[A-Za-z0-9_-]{3,128}$/.test(payload.threadId) &&
    typeof payload.pageHash === "string" &&
    /^[a-f0-9]{64}$/.test(payload.pageHash) &&
    typeof payload.iat === "number" &&
    Number.isSafeInteger(payload.iat) &&
    typeof payload.exp === "number" &&
    Number.isSafeInteger(payload.exp) &&
    payload.iat <= now + 30_000 &&
    payload.exp > now &&
    payload.exp > payload.iat &&
    payload.exp - payload.iat <= VIEWER_TOKEN_TTL_MS
  );
}

export function verifyPageToken(
  token: string,
  key: Uint8Array,
  expectedScope: PageTokenScope,
  now = Date.now(),
): PageTokenPayload | null {
  const parts = token.split(".");
  if (parts.length !== 2 || !parts[0] || !parts[1]) return null;
  const [encoded, suppliedSignature] = parts;

  try {
    const expected = createHmac("sha256", key)
      .update(encoded, "ascii")
      .digest();
    const supplied = Buffer.from(suppliedSignature, "base64url");
    if (supplied.byteLength !== expected.byteLength) return null;
    if (supplied.toString("base64url") !== suppliedSignature) return null;
    if (!timingSafeEqual(supplied, expected)) return null;

    const decoded = JSON.parse(
      Buffer.from(encoded, "base64url").toString("utf8"),
    ) as unknown;
    return isPageTokenPayload(decoded, expectedScope, now) ? decoded : null;
  } catch {
    return null;
  }
}

function jsonForInlineScript(value: unknown): string {
  return JSON.stringify(value)
    .replaceAll("<", "\\u003c")
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");
}

const DOCUMENT_CSS = String.raw`
:root{color-scheme:light dark;--bg:#f7f7f5;--surface:#fff;--ink:#191a1d;--muted:#656a73;--line:#dedfe2;--accent:#315fc5;--warn:#a54312;font:16px/1.55 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
@media(prefers-color-scheme:dark){:root{--bg:#111216;--surface:#191b20;--ink:#ececef;--muted:#a7abb3;--line:#30333a;--accent:#91aff1;--warn:#efa879}}
*{box-sizing:border-box}html{-webkit-text-size-adjust:100%}body{margin:0;background:var(--bg);color:var(--ink)}.thread-page{width:min(100% - 2rem,46rem);margin:0 auto;padding:clamp(2rem,7vw,5rem) 0 7rem}header{padding-bottom:1.5rem;margin-bottom:2rem;border-bottom:1px solid var(--line)}h1,h2,h3{line-height:1.2;text-wrap:balance}h1{margin:0;font-size:clamp(1.8rem,6vw,2.6rem);letter-spacing:-.025em}h2{margin-top:2.5rem}p,li{color:var(--muted)}a{color:var(--accent)}img,video,canvas,svg{max-width:100%;height:auto}pre{overflow:auto;padding:1rem;border:1px solid var(--line);border-radius:.65rem;background:var(--surface)}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}blockquote{margin-left:0;padding-left:1rem;border-left:3px solid var(--line)}.card,form{margin-top:1.5rem;padding:1.15rem;border:1px solid var(--line);border-radius:.75rem;background:var(--surface)}.needs-you{border-left:3px solid var(--warn);padding-left:1rem}.stale{margin:0 0 1.25rem;padding:.8rem 1rem;border:1px solid color-mix(in srgb,var(--warn) 45%,var(--line));border-radius:.65rem;color:var(--warn);background:color-mix(in srgb,var(--warn) 8%,var(--surface))}form>*+*{margin-top:1rem}fieldset{padding:0;border:0}legend,label{display:block;font-weight:600}label+label{margin-top:.65rem}label:has(>input[type=radio]),label:has(>input[type=checkbox]){display:flex;gap:.55rem;font-weight:400;color:var(--muted)}input,textarea,select,button{font:inherit}input[type=text],input[type=email],input[type=url],input[type=number],textarea,select{display:block;width:100%;margin-top:.4rem;padding:.55rem .65rem;color:var(--ink);background:var(--bg);border:1px solid var(--line);border-radius:.45rem}textarea{resize:vertical}button{padding:.55rem .85rem;border:1px solid var(--line);border-radius:.45rem;color:white;background:var(--accent);cursor:pointer}button+button{margin-left:.4rem}button:disabled,input:disabled,textarea:disabled,select:disabled{opacity:.55;cursor:not-allowed}[data-thread-page-status]{min-height:1.4em;margin:.75rem 0 0;font-size:.9rem;color:var(--muted)}:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
[data-thread-page-range]{display:inline-block;min-width:2.5rem;margin-left:.6rem;color:var(--ink);font-variant-numeric:tabular-nums}
.thread-page{width:min(calc(100% - 2rem),46rem);overflow-wrap:anywhere}
`;

const DOCUMENT_RUNTIME = String.raw`
const config=__THREAD_PAGE_CONFIG__;
const bridgeErrorCodes=new Set(["invalid_json","request_too_large","response_too_large","invalid_request","invalid_response","unsupported_version","unknown_method","invalid_params","stale_page","confirmation_required","confirmation_invalid","not_found","conflict","unavailable","cancelled","rate_limited","handler_error","invalid_result"]);
let dirty=false;
let customDirty=false;
let dirtySequence=0;
const dirtyFormVersions=new Map();
let bridgePort=null;
let requestSequence=0;
const pendingInvocations=new Map();
const queuedInvocationIds=[];
const pendingFormsById=new Map();
const pendingForms=new WeakSet();
const preparedRanges=new WeakSet();
let readOnly=Boolean(config.stale);
const sourceDisabled=new WeakSet();
function makeBridgeError(code,message){const error=new Error(message);error.name="ThreadPageBridgeError";Object.defineProperty(error,"code",{value:code,enumerable:true});return error}
function requestId(){requestSequence+=1;const random=globalThis.crypto&&typeof globalThis.crypto.randomUUID==="function"?globalThis.crypto.randomUUID():String(Date.now())+"-"+requestSequence;return "tp-"+random}
function exactKeys(value,wanted){if(!value||typeof value!=="object"||Array.isArray(value))return false;const keys=Object.keys(value);return keys.length===wanted.length&&wanted.every(function(key){return Object.prototype.hasOwnProperty.call(value,key)})}
function strictBridgeResponse(value){if(!value||typeof value!=="object"||Array.isArray(value)||value.v!==1||typeof value.id!=="string"||typeof value.ok!=="boolean")return false;if(value.ok===true)return exactKeys(value,["v","id","ok","result"]);return exactKeys(value,["v","id","ok","error"])&&exactKeys(value.error,["code","message"])&&bridgeErrorCodes.has(value.error.code)&&typeof value.error.message==="string"&&value.error.message.length>0&&value.error.message.length<=512}
function postPort(value){if(!bridgePort)return false;bridgePort.postMessage(value);return true}
function sendInvocation(id){const pending=pendingInvocations.get(id);if(!pending)return;try{postPort(pending.request)}catch(error){pendingInvocations.delete(id);pending.reject(makeBridgeError("invalid_request",error instanceof Error?error.message:"The request could not be sent"))}}
function flushInvocations(){while(queuedInvocationIds.length){const id=queuedInvocationIds.shift();if(id)sendInvocation(id)}}
function invoke(method,params){return new Promise(function(resolve,reject){const id=requestId();const request={v:1,id:id,method:method,params:params===undefined?null:params,pageRevision:config.pageRevision};pendingInvocations.set(id,{request:request,resolve:resolve,reject:reject});if(bridgePort)sendInvocation(id);else queuedInvocationIds.push(id)})}
function watch(method,params,listener,options){if(typeof listener!=="function")throw new TypeError("Thread Page watch needs a listener");const requested=options&&options.intervalMs;const interval=Number.isFinite(requested)?Math.max(2000,Math.min(300000,Math.round(requested))):8000;let stopped=false;let timer=null;let running=false;function schedule(delay){if(stopped)return;if(timer!==null)clearTimeout(timer);timer=setTimeout(tick,delay)}async function tick(){timer=null;if(stopped||running||document.visibilityState==="hidden")return;running=true;try{const value=await invoke(method,params);if(!stopped)listener(value,null)}catch(error){if(!stopped)listener(undefined,error)}finally{running=false;if(!stopped)schedule(interval)}}function visible(){if(stopped)return;if(document.visibilityState==="hidden"){if(timer!==null)clearTimeout(timer);timer=null}else schedule(0)}document.addEventListener("visibilitychange",visible);schedule(0);return function(){if(stopped)return;stopped=true;if(timer!==null)clearTimeout(timer);timer=null;document.removeEventListener("visibilitychange",visible)}}
function sendControl(kind,extra){if(!bridgePort)return false;try{bridgePort.postMessage(Object.assign({kind:kind},extra||{}));return true}catch{return false}}
function syncDirty(){const next=customDirty||dirtyFormVersions.size>0;if(next===dirty)return;dirty=next;sendControl(next?"thread-page:dirty":"thread-page:clean")}
function setDirty(next){customDirty=next!==false;syncDirty()}
function assetUrl(name){if(!config.assetBase)throw new Error("Thread Page assets are unavailable");const safe=String(name==null?"":name).replace(/^\.\//,"");if(!/^[A-Za-z0-9][A-Za-z0-9._-]{0,119}$/.test(safe)||safe.includes(".."))throw new TypeError("Thread Page asset names may only use letters, digits, dot, dash, and underscore, with no path segments");return config.assetBase+encodeURIComponent(safe)}
const threadPage=Object.freeze({version:1,invoke:invoke,watch:watch,setDirty:setDirty,assetUrl:assetUrl});
Object.defineProperty(window,"threadPage",{value:threadPage,writable:false,configurable:false,enumerable:true});
function statusFor(form){let node=form.querySelector("[data-thread-page-status]");if(!node){node=document.createElement("p");node.setAttribute("data-thread-page-status","");node.setAttribute("role","status");form.appendChild(node)}return node}
// The text of an element minus anything nested that is not part of the question:
// controls it wraps, hints, and plugin-injected nodes. A label that wraps its own
// input ("How deep? <input>") must read as just the question, and a <select>'s
// option text must never become part of its name.
function labelText(node){if(!node||typeof node.cloneNode!=="function")return "";const clone=node.cloneNode(true);if(typeof clone.querySelectorAll==="function"){Array.prototype.forEach.call(clone.querySelectorAll("input,textarea,select,button,option,small,output,[data-thread-page-range],[data-thread-page-status]"),function(element){element.remove()})}return String(clone.textContent||"").replace(/\s+/g," ").trim()}
function labelFor(form,name,group){const control=group&&group[0]||Array.from(form.elements).find(function(item){return item&&item.name===name});if(!control)return name;const explicitLabel=control.dataset&&control.dataset.label;if(explicitLabel)return String(explicitLabel).trim();const fieldset=control.closest&&control.closest("fieldset");if(fieldset){const legend=fieldset.querySelector("legend");const legendText=labelText(legend);if(legendText)return legendText}const aria=control.getAttribute&&control.getAttribute("aria-label");if(aria)return aria.trim();const wrapped=control.closest&&control.closest("label");if(wrapped){const wrappedText=labelText(wrapped);if(wrappedText)return wrappedText}if(control.id){const explicit=Array.from(document.querySelectorAll("label[for]")).find(function(label){return label.htmlFor===control.id});const forText=labelText(explicit);if(forText)return forText}return name}
function collect(form,submitter){const controls=Array.from(form.elements).filter(function(item){return item&&typeof item.name==="string"&&item.name&&!item.disabled});const answers=[];const seen=new Set();if(submitter){const actionValue=submitter.value||submitter.textContent.trim();answers.push({name:submitter.name||"action",label:"Action",value:actionValue});if(submitter.name)seen.add(submitter.name)}for(const control of controls){const name=control.name;const type=String(control.type||"").toLowerCase();if(seen.has(name)||["button","submit","reset","image","file"].includes(type))continue;seen.add(name);const group=controls.filter(function(item){return item.name===name});let value;if(type==="checkbox"){value=group.length===1?Boolean(control.checked):group.filter(function(item){return item.checked}).map(function(item){return item.value})}else if(type==="radio"){const checked=group.find(function(item){return item.checked});value=checked?checked.value:""}else if(control instanceof HTMLSelectElement&&control.multiple){value=Array.from(control.selectedOptions).map(function(option){return option.value})}else if(group.length>1){value=group.map(function(item){return String(item.value||"")})}else{value=String(control.value||"")}answers.push({name:name,label:labelFor(form,name,group),value:value})}return answers}
function syncOfflineBanner(){if(!document.body)return;let banner=document.querySelector("[data-thread-page-offline=plugin]");if(readOnly&&!banner){banner=document.createElement("aside");banner.setAttribute("data-thread-page-offline","plugin");banner.setAttribute("role","status");banner.setAttribute("style","position:relative;z-index:2147483647;margin:0;padding:.75rem 1rem;border-bottom:1px solid currentColor;font:600 14px/1.4 system-ui;background:Canvas;color:CanvasText");banner.textContent="Offline copy — responses are disabled until the source host reconnects.";document.body.insertBefore(banner,document.body.firstChild)}else if(!readOnly&&banner){banner.remove()}}
function matches(root,selector){return root&&typeof root.matches==="function"&&root.matches(selector)}
function descendants(root,selector){return root&&typeof root.querySelectorAll==="function"?Array.from(root.querySelectorAll(selector)):[]}
function formsIn(root){const forms=descendants(root,"form");if(matches(root,"form"))forms.unshift(root);return forms}
function isManualForm(form){return Boolean(form&&typeof form.hasAttribute==="function"&&form.hasAttribute("data-thread-page-manual"))}
function autoFormsIn(root){return formsIn(root).filter(function(form){return !isManualForm(form)})}
function controlsIn(root){const selector="form input,form textarea,form select,form button";const controls=descendants(root,selector);if(matches(root,selector))controls.unshift(root);return controls}
function prepareRanges(form){descendants(form,'input[type="range"]').forEach(function(input){if(preparedRanges.has(input))return;preparedRanges.add(input);const output=document.createElement("output");output.setAttribute("data-thread-page-range","");const sync=function(){output.textContent=String(input.value)};input.addEventListener("input",sync);sync();input.insertAdjacentElement("afterend",output)})}
function prepareRoot(root){const forms=autoFormsIn(root);forms.forEach(function(form){form.noValidate=true;prepareRanges(form)});if(!readOnly)return;controlsIn(root).forEach(function(control){if(!control.disabled){sourceDisabled.add(control);control.disabled=true}});forms.forEach(function(form){statusFor(form).textContent="Offline copy — responses are disabled"})}
function applyReadOnly(next){readOnly=next;const forms=autoFormsIn(document);forms.forEach(function(form){form.noValidate=true});controlsIn(document).forEach(function(control){if(next){if(!control.disabled){sourceDisabled.add(control);control.disabled=true}}else if(sourceDisabled.has(control)){sourceDisabled.delete(control);control.disabled=false}});forms.forEach(function(form){const status=statusFor(form);if(next)status.textContent="Offline copy — responses are disabled";else if(status.textContent==="Offline copy — responses are disabled")status.textContent=""});syncOfflineBanner()}
function initialize(){prepareRoot(document);syncOfflineBanner()}
initialize();
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initialize,{once:true});
if(typeof MutationObserver==="function"&&document.documentElement){const observer=new MutationObserver(function(records){records.forEach(function(record){Array.from(record.addedNodes||[]).forEach(prepareRoot)});syncOfflineBanner()});observer.observe(document.documentElement,{childList:true,subtree:true})}
function markFormDirty(event){const target=event&&event.target;const form=target&&typeof target.closest==="function"?target.closest("form"):null;if(!form||isManualForm(form))return;dirtySequence+=1;dirtyFormVersions.set(form,dirtySequence);syncDirty()}
document.addEventListener("input",markFormDirty,true);
document.addEventListener("change",markFormDirty,true);
function filesIn(form){const out=[];descendants(form,'input[type="file"]').forEach(function(input){if(input.disabled)return;Array.prototype.forEach.call(input.files||[],function(file){if(out.length<8)out.push({field:input.name||"file",file:file})})});return out}
document.addEventListener("submit",function(event){const form=event.target;if(!(form instanceof HTMLFormElement)||isManualForm(form))return;event.preventDefault();if(readOnly||pendingForms.has(form))return;const submissionId=requestId();const buttons=Array.from(form.querySelectorAll("button")).filter(function(button){return !button.disabled});const formVersion=dirtyFormVersions.get(form);pendingFormsById.set(submissionId,{form:form,buttons:buttons,formVersion:formVersion});pendingForms.add(form);const answers=collect(form,event.submitter);const files=filesIn(form);buttons.forEach(function(button){button.disabled=true});statusFor(form).textContent=files.length?"Uploading…":"Sending…";const heading=document.querySelector("h1");if(!sendControl("thread-page:submit",{submissionId:submissionId,pageHash:config.pageRevision,title:form.dataset.title||(heading?heading.textContent.trim():"Thread Page"),answers:answers,files:files})){pendingFormsById.delete(submissionId);pendingForms.delete(form);statusFor(form).textContent="Page connection is not ready";buttons.forEach(function(button){button.disabled=false})}},true);
function onPortMessage(event){const data=event&&event.data;if(!data||typeof data!=="object")return;if(data.kind==="thread-page:source-state"){applyReadOnly(Boolean(data.stale));return}if(data.kind==="thread-page:submit-progress"){const progressForm=pendingFormsById.get(data.submissionId);if(progressForm)statusFor(progressForm.form).textContent=String(data.message||"Working…").slice(0,120);return}if(data.kind==="thread-page:submit-result"){const pendingForm=pendingFormsById.get(data.submissionId);if(!pendingForm)return;pendingFormsById.delete(data.submissionId);pendingForms.delete(pendingForm.form);statusFor(pendingForm.form).textContent=data.ok?(data.message||"Sent"):(data.error||"Could not send");pendingForm.buttons.forEach(function(button){if(readOnly)sourceDisabled.add(button);else button.disabled=false});if(data.ok&&dirtyFormVersions.get(pendingForm.form)===pendingForm.formVersion){dirtyFormVersions.delete(pendingForm.form);syncDirty()}return}const possibleId=typeof data.id==="string"?data.id:"";const pending=pendingInvocations.get(possibleId);if(!pending)return;pendingInvocations.delete(possibleId);if(!strictBridgeResponse(data)){pending.reject(makeBridgeError("invalid_response","The Thread Page bridge returned an invalid response"));return}if(data.ok)pending.resolve(data.result);else pending.reject(makeBridgeError(data.error.code,data.error.message))}
function acceptPort(event){if(bridgePort||event.source!==parent||!event.data||event.data.kind!=="thread-page:connect"||event.data.version!==1||!event.ports||event.ports.length!==1)return;if(typeof event.stopImmediatePropagation==="function")event.stopImmediatePropagation();bridgePort=event.ports[0];bridgePort.onmessage=onPortMessage;if(typeof bridgePort.start==="function")bridgePort.start();flushInvocations();if(dirty)sendControl("thread-page:dirty")}
window.addEventListener("message",acceptPort,true);
if(readOnly)applyReadOnly(true);
parent.postMessage({kind:"thread-page:ready",version:1},"*");
`;

type HtmlDocument = DefaultTreeAdapterTypes.Document;
type HtmlElement = DefaultTreeAdapterTypes.Element;

interface AuthoredDocument {
  document: HtmlDocument;
  injectionParent: HtmlElement;
}

function directHtmlChild(
  parent: HtmlDocument | HtmlElement,
  tagName: string,
): HtmlElement | null {
  for (const child of parent.childNodes) {
    if (
      defaultTreeAdapter.isElementNode(child) &&
      child.tagName === tagName &&
      child.namespaceURI === "http://www.w3.org/1999/xhtml"
    ) {
      return child;
    }
  }
  return null;
}

function parseAuthoredDocument(source: string): AuthoredDocument | null {
  // A BOM at the beginning of an HTML byte stream is an encoding signature,
  // not a text node. parse5 accepts strings, so remove it before tokenization.
  const browserSource = source.charCodeAt(0) === 0xfeff ? source.slice(1) : source;
  const document = parseHtml(browserSource, {
    scriptingEnabled: true,
    sourceCodeLocationInfo: true,
  });
  const html = directHtmlChild(document, "html");
  if (!html) return null;

  const head = directHtmlChild(html, "head");
  const body = directHtmlChild(html, "body");
  const frameset = directHtmlChild(html, "frameset");
  const hasHtmlDoctype = document.childNodes.some(
    (child) =>
      defaultTreeAdapter.isDocumentTypeNode(child) &&
      child.name.toLowerCase() === "html",
  );
  const hasAuthoredShell = [html, head, body, frameset].some(
    (element) => element?.sourceCodeLocation != null,
  );

  if (!hasHtmlDoctype && !hasAuthoredShell) return null;
  return { document, injectionParent: head ?? body ?? frameset ?? html };
}

function injectKernel(
  authored: AuthoredDocument,
  runtime: string,
  nonce: string,
  assetBase?: string | null,
): string {
  const script = defaultTreeAdapter.createElement(
    "script",
    authored.injectionParent.namespaceURI,
    [
      { name: "data-thread-page-kernel", value: "" },
      { name: "nonce", value: nonce },
    ],
  );
  defaultTreeAdapter.insertText(script, runtime);

  // The first <base> in a document wins, so the confined asset preview is
  // injected ahead of any authored one. Relative page resources therefore
  // resolve inside the thread's asset directory and nowhere else.
  const nodes = assetBase
    ? [
        defaultTreeAdapter.createElement(
          "base",
          authored.injectionParent.namespaceURI,
          [{ name: "href", value: assetBase }],
        ),
        script,
      ]
    : [script];

  // Insert in order at the very front of the injection parent.
  const anchor = defaultTreeAdapter.getFirstChild(authored.injectionParent);
  for (const node of nodes) {
    if (anchor) {
      defaultTreeAdapter.insertBefore(authored.injectionParent, node, anchor);
    } else {
      defaultTreeAdapter.appendChild(authored.injectionParent, node);
    }
  }

  return serializeHtml(authored.document);
}

export function renderDocument(options: {
  fragment: string;
  nonce: string;
  pageHash: string;
  stale: boolean;
  assetBase?: string | null;
}): string {
  const config = jsonForInlineScript({
    pageRevision: options.pageHash,
    stale: options.stale,
    assetBase: options.assetBase ?? null,
  });
  const runtime = DOCUMENT_RUNTIME.replace("__THREAD_PAGE_CONFIG__", config);
  const kernel = `<script data-thread-page-kernel nonce="${escapeHtml(options.nonce)}">${runtime}</script>`;

  const authoredDocument = parseAuthoredDocument(options.fragment);
  if (authoredDocument) {
    return injectKernel(
      authoredDocument,
      runtime,
      options.nonce,
      options.assetBase,
    );
  }

  const staleBanner = options.stale
    ? '<aside class="stale" data-thread-page-offline="plugin" role="status"><strong>Offline copy.</strong> The source host is unavailable. This cached page is read-only until it reconnects.</aside>'
    : "";

  const base = options.assetBase
    ? `<base href="${escapeHtml(options.assetBase)}">\n`
    : "";

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="light dark">
<title>Thread Page</title>
${base}<style nonce="${escapeHtml(options.nonce)}">${DOCUMENT_CSS}</style>
${kernel}
</head>
<body>
<div class="thread-page">${staleBanner}${options.fragment}</div>
</body>
</html>`;
}

const OUTER_CSS = String.raw`
:root{color-scheme:light dark;font:14px/1.4 ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--bg:#f7f7f5;--surface:#fff;--ink:#17181b;--muted:#676c75;--line:#dfe0e3;--accent:#315fc5;--warn:#a54312} @media(prefers-color-scheme:dark){:root{--bg:#111216;--surface:#191b20;--ink:#eeeef0;--muted:#a5a9b1;--line:#30333a;--accent:#91aff1;--warn:#efa879}}*{box-sizing:border-box}html,body{height:100%;margin:0;background:var(--bg);color:var(--ink)}.shell{display:grid;grid-template-rows:auto 1fr;height:100%;min-height:100dvh}.bar{display:flex;align-items:center;gap:.75rem;min-height:2.5rem;padding:.45rem max(.7rem,env(safe-area-inset-right)) .45rem max(.7rem,env(safe-area-inset-left));border-bottom:1px solid var(--line);background:var(--surface)}.home{flex:none;color:var(--muted);text-decoration:none;font-weight:600;white-space:nowrap}.home:hover{color:var(--ink)}.title{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:600}.status{margin-left:auto;color:var(--muted);text-align:right}.status[data-tone=warn]{color:var(--warn)}
.work{flex:none;display:none;align-items:center;gap:.4rem;color:var(--muted)}.work[data-visible=true]{display:inline-flex}.work .dot{width:.5rem;height:.5rem;border-radius:50%;background:var(--accent)}@media(prefers-reduced-motion:no-preference){.work[data-visible=true] .dot{animation:tp-pulse 1.4s ease-in-out infinite}}@keyframes tp-pulse{0%,100%{opacity:1}50%{opacity:.25}}button{display:none;padding:.25rem .55rem;border:1px solid var(--line);border-radius:.4rem;color:var(--ink);background:var(--bg);cursor:pointer}button[data-visible=true]{display:inline-block}iframe{display:block;width:100%;height:100%;border:0;background:var(--bg)}
dialog{margin:auto;max-width:min(30rem,calc(100vw - 2rem));padding:1.15rem 1.25rem;border:1px solid var(--line);border-radius:.75rem;color:var(--ink);background:var(--surface)}dialog::backdrop{background:rgb(0 0 0 / .45)}dialog h2{margin:0 0 .5rem;font-size:1rem}dialog p{margin:0 0 1rem;color:var(--muted);overflow-wrap:anywhere}dialog .row{display:flex;gap:.5rem;justify-content:flex-end}dialog button{display:inline-block}dialog button[value=confirm]{color:#fff;background:var(--accent);border-color:var(--accent)}
`;

const OUTER_RUNTIME = String.raw`
const config=__THREAD_PAGE_CONFIG__;
const frame=document.querySelector("iframe");
const status=document.querySelector(".status");
const reloadButton=document.querySelector("button");
const bridgeErrorCodes=new Set(["invalid_json","request_too_large","response_too_large","invalid_request","invalid_response","unsupported_version","unknown_method","invalid_params","stale_page","confirmation_required","confirmation_invalid","not_found","conflict","unavailable","cancelled","rate_limited","handler_error","invalid_result"]);
let dirty=false;
let etag='"'+config.pageRevision+'"';
let polling=false;
let stopped=false;
let lastStale=Boolean(config.stale);
let timer=null;
let controller=null;
let framePort=null;
let awaitingReady=true;
function setStatus(text,warn){status.textContent=text||"";status.dataset.tone=warn?"warn":""}
/* The page you are reading is whatever was last saved, so the useful sentence is
   not "loading" but that another version is coming. Driven by a header on the
   revision poll the shell already makes, so no page and no agent implements it. */
function setWorking(state){const strip=document.querySelector(".work");if(!strip)return;const label=strip.querySelector(".what");const working=state==="working"&&Boolean(config.workingLabel);strip.dataset.visible=working?"true":"false";if(label)label.textContent=config.workingLabel||""}
function exactKeys(value,wanted){if(!value||typeof value!=="object"||Array.isArray(value))return false;const keys=Object.keys(value);return keys.length===wanted.length&&wanted.every(function(key){return Object.prototype.hasOwnProperty.call(value,key)})}
function validId(value){return typeof value==="string"&&value.length>=1&&value.length<=96&&/^[A-Za-z0-9][A-Za-z0-9._:-]*$/.test(value)}
function safeId(value){return validId(value)?value:"invalid"}
function failure(id,code,message){return {v:1,id:safeId(id),ok:false,error:{code:code,message:message}}}
function strictBridgeRequest(value){return exactKeys(value,["v","id","method","params","pageRevision"])&&value.v===1&&validId(value.id)&&typeof value.method==="string"&&value.method.length>=3&&value.method.length<=96&&/^[a-z][a-zA-Z0-9]*(?:\.[a-z][a-zA-Z0-9]*)+$/.test(value.method)&&typeof value.pageRevision==="string"&&value.pageRevision===config.pageRevision}
function strictBridgeResponse(value,id){if(!value||typeof value!=="object"||Array.isArray(value)||value.v!==1||value.id!==id||typeof value.ok!=="boolean")return false;if(value.ok===true)return exactKeys(value,["v","id","ok","result"]);return exactKeys(value,["v","id","ok","error"])&&exactKeys(value.error,["code","message"])&&bridgeErrorCodes.has(value.error.code)&&typeof value.error.message==="string"&&value.error.message.length>0&&value.error.message.length<=512}
function closeFramePort(){if(framePort&&typeof framePort.close==="function")framePort.close();framePort=null}
function navigateFrame(url){closeFramePort();awaitingReady=true;frame.src=url}
function reloadFrame(){dirty=false;reloadButton.dataset.visible="false";navigateFrame(config.documentUrl+(config.documentUrl.includes("?")?"&":"?")+"reload="+Date.now())}
function schedule(delay){if(timer!==null)clearTimeout(timer);timer=null;if(!stopped&&document.visibilityState==="visible")timer=setTimeout(function(){timer=null;void poll()},delay)}
function pause(){if(timer!==null)clearTimeout(timer);timer=null;if(controller){controller.abort();controller=null}}
reloadButton.addEventListener("click",function(){location.reload()});
/* Navigation belongs to the trusted shell: the sandboxed frame cannot reach
   top-level context, and these destinations are built here from an id the
   server has already validated, never from page-supplied markup or a URL. */
function navigateTo(port,request){const params=request.params;const id=params&&typeof params.threadId==="string"?params.threadId:"";if(!/^[A-Za-z0-9_-]{3,128}$/.test(id)){port.postMessage(failure(request.id,"invalid_params","A valid threadId is required"));return}const url=request.method==="threads.openPage"?config.pageUrlTemplate.replace("__THREAD__",encodeURIComponent(id)):config.bbThreadUrlTemplate.replace("__THREAD__",encodeURIComponent(id));try{window.open(url,"_blank","noopener");port.postMessage({v:1,id:request.id,ok:true,result:{opened:true}})}catch(error){port.postMessage(failure(request.id,"unavailable",error instanceof Error?error.message:"Could not open that destination"))}}
/* Leaving bb entirely needs a confirmation the page cannot word, and the URL is
   re-parsed here rather than trusted as a string. */
async function openExternal(port,request){const params=request.params;const raw=params&&typeof params.url==="string"?params.url:"";let target=null;try{target=new URL(raw)}catch{target=null}if(!target||(target.protocol!=="http:"&&target.protocol!=="https:")){port.postMessage(failure(request.id,"invalid_params","Only http and https destinations can be opened"));return}const label=params&&typeof params.label==="string"?params.label:"";const summary="Leave bb and open "+(label?'\u201c'+label.slice(0,80)+'\u201d at ':"")+target.origin;if(!await confirmInChrome(summary)){port.postMessage(failure(request.id,"cancelled","You declined this action"));return}try{window.open(target.href,"_blank","noopener,noreferrer");port.postMessage({v:1,id:request.id,ok:true,result:{opened:true}})}catch(error){port.postMessage(failure(request.id,"unavailable",error instanceof Error?error.message:"Could not open that destination"))}}
async function relayBridge(port,request){if(!strictBridgeRequest(request)){port.postMessage(failure(request&&request.id,"invalid_request","Invalid Thread Page bridge request"));return}if(request.method==="threads.openPage"||request.method==="threads.openBb"){navigateTo(port,request);return}if(request.method==="navigation.openExternal"){void openExternal(port,request);return}try{const response=await fetch(config.bridgeUrl,{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"content-type":"application/json"},body:JSON.stringify({actionToken:config.actionToken,request:request})});const body=await response.json().catch(function(){return null});
/* The server answers a confirmed method with a signed challenge and its own
   summary. We show that summary, never the page's. */
if(response.status===401&&body&&body.confirm&&typeof body.confirm.challenge==="string"&&typeof body.confirm.summary==="string"&&body.confirm.requestId===request.id){await relayConfirmedBridge(port,request,body.confirm.challenge,body.confirm.summary);return}
port.postMessage(strictBridgeResponse(body,request.id)?body:failure(request.id,"invalid_response","The Thread Page bridge returned an invalid response"))}catch(error){port.postMessage(failure(request.id,"unavailable",error instanceof Error?error.message:"The Thread Page bridge is unavailable"))}}
const MAX_UPLOAD_BYTES=24*1024*1024;
// bb's local auth requires an application/json body on non-GET requests, which
// is what forces the CORS preflight. The bytes therefore travel base64-encoded
// inside a JSON envelope rather than as a raw body.
function encodeBase64(buffer){const bytes=new Uint8Array(buffer);let binary="";const chunk=0x8000;for(let index=0;index<bytes.length;index+=chunk)binary+=String.fromCharCode.apply(null,bytes.subarray(index,index+chunk));return btoa(binary)}
async function uploadOne(entry){if(!(entry&&entry.file&&typeof entry.file.size==="number"))throw new Error("Attachment is not a file");if(entry.file.size<=0)throw new Error("Attachment "+(entry.file.name||"file")+" is empty");if(entry.file.size>MAX_UPLOAD_BYTES)throw new Error("Attachment "+(entry.file.name||"file")+" is larger than 24 MiB");const content=encodeBase64(await entry.file.arrayBuffer());const response=await fetch(config.uploadUrl,{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"content-type":"application/json"},body:JSON.stringify({actionToken:config.actionToken,name:String(entry.file.name||"upload"),content:content})});const body=await response.json().catch(function(){return null});if(!response.ok||!body||body.ok!==true)throw new Error((body&&body.error)||"Upload failed ("+response.status+")");return {field:String(entry.field||"file").slice(0,128),name:body.name,path:body.path,sizeBytes:body.sizeBytes}}
async function uploadAll(port,data){const entries=Array.isArray(data.files)?data.files.slice(0,8):[];const files=[];for(let index=0;index<entries.length;index+=1){port.postMessage({kind:"thread-page:submit-progress",submissionId:data.submissionId,message:"Uploading "+(index+1)+" of "+entries.length+"\u2026"});files.push(await uploadOne(entries[index]))}return files}
async function relaySubmit(port,data){try{const files=await uploadAll(port,data);if(files.length)port.postMessage({kind:"thread-page:submit-progress",submissionId:data.submissionId,message:"Sending\u2026"});const response=await fetch(config.submitUrl,{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"content-type":"application/json"},body:JSON.stringify({actionToken:config.actionToken,submissionId:data.submissionId,pageHash:config.pageRevision,title:data.title,answers:data.answers,files:files})});const body=await response.json().catch(function(){return {ok:false,error:"Invalid server response"}});port.postMessage({kind:"thread-page:submit-result",submissionId:data.submissionId,ok:response.ok&&body.ok===true,message:body.delivery?"Sent ("+body.delivery+")":"Sent",error:body.error||("Request failed ("+response.status+")")})}catch(error){port.postMessage({kind:"thread-page:submit-result",submissionId:data.submissionId,ok:false,error:error instanceof Error?error.message:"Request failed"})}}
/* A confirmed action is described by the server and shown here, in trusted
   chrome the sandboxed page cannot draw over, click, or reword. The page never
   supplies this text and never sees the challenge. */
function confirmInChrome(summary){return new Promise(function(resolve){const dialog=document.querySelector("dialog");const text=dialog.querySelector("p");text.textContent=summary;let settled=false;function finish(value){if(settled)return;settled=true;dialog.removeEventListener("close",onClose);resolve(value)}function onClose(){finish(dialog.returnValue==="confirm")}dialog.addEventListener("close",onClose);dialog.returnValue="";if(typeof dialog.showModal==="function")dialog.showModal();else finish(false)})}
async function relayConfirmedBridge(port,request,challenge,summary){const approved=await confirmInChrome(summary);if(!approved){port.postMessage(failure(request.id,"cancelled","You declined this action"));return}try{const response=await fetch(config.bridgeUrl,{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"content-type":"application/json"},body:JSON.stringify({actionToken:config.actionToken,request:request,confirmation:challenge})});const body=await response.json().catch(function(){return null});port.postMessage(strictBridgeResponse(body,request.id)?body:failure(request.id,"invalid_response","The Thread Page bridge returned an invalid response"))}catch(error){port.postMessage(failure(request.id,"unavailable",error instanceof Error?error.message:"The Thread Page bridge is unavailable"))}}
function onFramePortMessage(port,event){const data=event&&event.data;if(!data||typeof data!=="object")return;if(data.kind==="thread-page:dirty"){dirty=true;return}if(data.kind==="thread-page:clean"){dirty=false;return}if(data.kind==="thread-page:submit"){void relaySubmit(port,data);return}void relayBridge(port,data)}
function connectFrame(){const channel=new MessageChannel();const port=channel.port1;framePort=port;port.onmessage=function(event){onFramePortMessage(port,event)};if(typeof port.start==="function")port.start();frame.contentWindow.postMessage({kind:"thread-page:connect",version:1},"*",[channel.port2]);port.postMessage({kind:"thread-page:source-state",stale:lastStale})}
window.addEventListener("message",function(event){if(!awaitingReady||event.origin!=="null"||event.source!==frame.contentWindow||!event.data||event.data.kind!=="thread-page:ready"||event.data.version!==1)return;awaitingReady=false;connectFrame()});
async function poll(){if(stopped||polling||document.visibilityState!=="visible")return;if(Date.now()>=config.expiresAt-30000){if(dirty){stopped=true;setStatus("Session expiring — reload when ready",true);reloadButton.dataset.visible="true"}else location.reload();return}polling=true;controller=new AbortController();try{const response=await fetch(config.documentUrl,{method:"GET",credentials:"same-origin",cache:"no-store",headers:{"if-none-match":etag},signal:controller.signal});if(response.status===401){stopped=true;setStatus("Session expired — reload this page",true);reloadButton.dataset.visible="true";return}if(!response.ok&&response.status!==304){setStatus("Page unavailable",true);return}const stale=response.headers.get("x-thread-page-stale")==="true";setWorking(response.headers.get("x-thread-page-activity"));const next=response.headers.get("etag");if(stale!==lastStale){lastStale=stale;if(framePort)framePort.postMessage({kind:"thread-page:source-state",stale:stale});if(!dirty)reloadFrame()}if(stale)setStatus("Offline copy — read-only",true);else setStatus("",false);if(next&&next!==etag){if(dirty){setStatus("Page changed — reload when ready",true);reloadButton.dataset.visible="true"}else location.reload()}etag=next||etag}catch(error){if(!(error instanceof DOMException&&error.name==="AbortError"))setStatus("Cannot check for updates",true)}finally{controller=null;polling=false;schedule(10000)}}
document.addEventListener("visibilitychange",function(){if(document.visibilityState==="visible")schedule(0);else pause()});
navigateFrame(config.documentUrl);
schedule(10000);
`;

export function renderOuterPage(options: {
  nonce: string;
  title: string;
  actionToken: string;
  pageHash: string;
  expiresAt: number;
  documentUrl: string;
  submitUrl: string;
  uploadUrl: string;
  bridgeUrl: string;
  pageUrlTemplate: string;
  bbThreadUrlTemplate: string;
  /** Omitted when this page is itself home, or when no home is set. */
  homeUrl: string | null;
  /** Whether the owning thread is mid-turn right now. */
  working: boolean;
  /** User-adjustable wording for the working strip. */
  workingLabel: string;
  stale: boolean;
}): string {
  const config = jsonForInlineScript({
    actionToken: options.actionToken,
    pageRevision: options.pageHash,
    expiresAt: options.expiresAt,
    documentUrl: options.documentUrl,
    submitUrl: options.submitUrl,
    uploadUrl: options.uploadUrl,
    bridgeUrl: options.bridgeUrl,
    pageUrlTemplate: options.pageUrlTemplate,
    bbThreadUrlTemplate: options.bbThreadUrlTemplate,
    workingLabel: options.workingLabel,
    stale: options.stale,
  });
  const runtime = OUTER_RUNTIME.replace("__THREAD_PAGE_CONFIG__", config);
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="color-scheme" content="light dark">
<title>${escapeHtml(options.title)}</title>
<style nonce="${escapeHtml(options.nonce)}">${OUTER_CSS}</style>
</head>
<body>
<div class="shell">
  <header class="bar">
    ${
      options.homeUrl
        ? `<a class="home" href="${escapeHtml(options.homeUrl)}" title="All sessions">← Sessions</a>`
        : ""
    }
    <span class="title">${escapeHtml(options.title)}</span>
    <span class="work" role="status" data-visible="${options.working && options.workingLabel ? "true" : "false"}"><span class="dot" aria-hidden="true"></span><span class="what">${escapeHtml(options.workingLabel)}</span></span>
    <span class="status" role="status"${options.stale ? ' data-tone="warn"' : ""}>${options.stale ? "Offline copy — read-only" : ""}</span>
    <button type="button" aria-label="Reload updated page">Reload</button>
  </header>
  <iframe title="${escapeHtml(options.title)}" sandbox="allow-scripts allow-forms" referrerpolicy="no-referrer"></iframe>
</div>
<dialog aria-labelledby="tp-confirm-title">
  <form method="dialog">
    <h2 id="tp-confirm-title">Confirm this action</h2>
    <p></p>
    <div class="row">
      <button value="cancel">Cancel</button>
      <button value="confirm">Confirm</button>
    </div>
  </form>
</dialog>
<script nonce="${escapeHtml(options.nonce)}">${runtime}</script>
</body>
</html>`;
}

export function formatSubmissionMessage(submission: Submission): string {
  const heading = submission.title.trim() || "Thread Page";
  const fields = submission.answers.map((answer) => {
    const label = answer.label.trim() || answer.name;
    const value = Array.isArray(answer.value)
      ? answer.value.length > 0
        ? answer.value.join(", ")
        : "(left blank)"
      : typeof answer.value === "boolean"
        ? answer.value
          ? "Yes"
          : "No"
        : answer.value.length > 0
          ? answer.value
          : "(left blank)";
    return `**${label}**\n${value}`;
  });
  const attachments = submission.files.length
    ? [
        [
          "**Attached files**",
          ...submission.files.map(
            (file) =>
              `- \`$BB_THREAD_STORAGE/${file.path}\` (${file.name}, ${file.sizeBytes} bytes)`,
          ),
          "Read them from thread storage with your normal tools.",
        ].join("\n"),
      ]
    : [];
  return [
    `The user answered the form on your Thread Page — ${heading}.`,
    ...fields,
    ...attachments,
  ].join("\n\n");
}

export function formatThreadReplyMessage(
  title: string | undefined,
  result: unknown,
): string {
  const heading = title?.trim() || "Interactive response";
  const serialized = JSON.stringify(result, null, 2) ?? "null";
  let longestBacktickRun = 0;
  for (const match of serialized.matchAll(/`+/g)) {
    longestBacktickRun = Math.max(longestBacktickRun, match[0].length);
  }
  const fence = "`".repeat(Math.max(3, longestBacktickRun + 1));
  return [
    `The user sent an interactive response from your Thread Page — ${heading}.`,
    `**Result**\n\n${fence}json\n${serialized}\n${fence}`,
  ].join("\n\n");
}

export function parseSubmission(value: unknown): Submission | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const input = value as Record<string, unknown>;
  if (
    typeof input.actionToken !== "string" ||
    input.actionToken.length > 4096 ||
    typeof input.submissionId !== "string" ||
    !/^[A-Za-z0-9._-]{1,128}$/.test(input.submissionId) ||
    typeof input.pageHash !== "string" ||
    !/^[a-f0-9]{64}$/.test(input.pageHash) ||
    typeof input.title !== "string" ||
    input.title.length > 300 ||
    !Array.isArray(input.answers) ||
    input.answers.length > 64
  ) {
    return null;
  }

  let total = input.title.length;
  const answers: FormAnswer[] = [];
  for (const raw of input.answers) {
    if (!raw || typeof raw !== "object" || Array.isArray(raw)) return null;
    const answer = raw as Record<string, unknown>;
    if (
      typeof answer.name !== "string" ||
      answer.name.length > 128 ||
      typeof answer.label !== "string" ||
      answer.label.length > 300 ||
      !isAnswerValue(answer.value)
    ) {
      return null;
    }
    const valueLength = Array.isArray(answer.value)
      ? answer.value.reduce((sum, item) => sum + item.length, 0)
      : typeof answer.value === "string"
        ? answer.value.length
        : 1;
    total += answer.name.length + answer.label.length + valueLength;
    if (total > 32_000) return null;
    answers.push({
      name: answer.name,
      label: answer.label,
      value: answer.value,
    });
  }

  const files: SubmissionFile[] = [];
  if (input.files !== undefined) {
    if (!Array.isArray(input.files) || input.files.length > 8) return null;
    for (const raw of input.files) {
      if (!raw || typeof raw !== "object" || Array.isArray(raw)) return null;
      const file = raw as Record<string, unknown>;
      if (
        typeof file.field !== "string" ||
        file.field.length > 128 ||
        typeof file.name !== "string" ||
        file.name.length > 80 ||
        file.name !== safeUploadName(file.name) ||
        typeof file.path !== "string" ||
        file.path.length > 300 ||
        !file.path.startsWith(`${UPLOAD_DIRNAME}/`) ||
        file.path.includes("..") ||
        typeof file.sizeBytes !== "number" ||
        !Number.isSafeInteger(file.sizeBytes) ||
        file.sizeBytes < 0 ||
        file.sizeBytes > MAX_UPLOAD_BYTES
      ) {
        return null;
      }
      files.push({
        field: file.field,
        name: file.name,
        path: file.path,
        sizeBytes: file.sizeBytes,
      });
    }
  }

  return {
    actionToken: input.actionToken,
    submissionId: input.submissionId,
    pageHash: input.pageHash,
    title: input.title,
    answers,
    files,
  };
}

function isAnswerValue(value: unknown): value is FormAnswerValue {
  if (typeof value === "boolean") return true;
  if (typeof value === "string") return value.length <= 8_000;
  return (
    Array.isArray(value) &&
    value.length <= 64 &&
    value.every((item) => typeof item === "string" && item.length <= 2_000)
  );
}
