// Bundles the browser runtimes (kernel and shell) into string modules the
// server bundle embeds. `bb plugin build` has no text loader, so this is the
// step that keeps runtime code readable TypeScript in src/runtime/ while the
// git-installable artefact needs no build of its own.
//
//   node scripts/build-runtime.mjs          write src/generated/*.ts
//   node scripts/build-runtime.mjs --check  exit 1 when a committed file is stale

import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export const RUNTIMES = [
  {
    name: "kernel",
    entry: "src/runtime/kernel/main.ts",
    out: "src/generated/kernel-runtime.ts",
    constant: "KERNEL_RUNTIME",
  },
  {
    name: "shell",
    entry: "src/runtime/shell/main.ts",
    out: "src/generated/shell-runtime.ts",
    constant: "SHELL_RUNTIME",
  },
];

export async function bundleRuntime(runtime) {
  const result = await build({
    entryPoints: [resolve(root, runtime.entry)],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2020",
    minify: true,
    legalComments: "none",
    logLevel: "error",
  });
  const code = result.outputFiles[0].text.trim();
  if (code.includes("</script")) {
    throw new Error(`${runtime.name}: bundle contains a script terminator`);
  }
  return [
    "// Generated by scripts/build-runtime.mjs from " + runtime.entry + ".",
    "// Do not edit; run `npm run build:runtime`.",
    `export const ${runtime.constant} = ${JSON.stringify(code)};`,
    "",
  ].join("\n");
}

async function main() {
  const check = process.argv.includes("--check");
  let stale = false;
  for (const runtime of RUNTIMES) {
    const generated = await bundleRuntime(runtime);
    const outPath = resolve(root, runtime.out);
    if (check) {
      const current = await readFile(outPath, "utf8").catch(() => "");
      if (current !== generated) {
        stale = true;
        console.error(`stale: ${runtime.out}`);
      }
      continue;
    }
    await mkdir(dirname(outPath), { recursive: true });
    await writeFile(outPath, generated);
    console.log(`wrote ${runtime.out} (${generated.length} bytes)`);
  }
  if (stale) process.exit(1);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
