// Re-exports of the pure domain.
export { LIMITS, mebibytes, kibibytes, type Limits } from "./limits.ts";
export { BRIDGE_ERROR_CODES, STATUS_BY_CODE, PUBLIC_MESSAGES, PageError, boundedMessage, errorText, isBridgeErrorCode, mapProviderError, type BridgeErrorCode, type PageErrorCode, type LogSink } from "./errors.ts";
export { HOME_IDENTITY, isSessionId, isSessionIdentity, isEntityId, isRequestId, isMethodName, isRevision, isOpaqueToken, isStorageKey, isSubmissionId } from "./ids.ts";
export { revisionOf, sha256Hex, EMPTY_REVISION, etagFor, ifNoneMatchMatches } from "./revision.ts";
export { validateJson, parseStrictJson, utf8Bytes, boundIssue, isJsonObject, type JsonValue, type JsonObject, type Validation, type Issue } from "./json/strict-json.ts";
export { canonicalJson, fingerprint } from "./json/canonical.ts";
export { escapeHtml, escapeAttribute, jsonForScript } from "./html/escape.ts";
export { injectKernel, wrapFragment, parseDocument, serialize, KERNEL_ATTRIBUTE, type InjectionOptions } from "./html/document.ts";
export { captureForms, firstHeading, MANUAL_ATTRIBUTE, TITLE_ATTRIBUTE } from "./html/forms.ts";
export { matchForm, formKey, controlKey, normalizeTitle, type FormIdentity, type WantedForm } from "./forms/identity.ts";
export { ENTRY_DOCUMENT, UPLOAD_DIR, isDocumentPath, isPartPath, directoryOf, documentKey, documentFragment, checkDocumentQuery, splitDocumentUrl, RESERVED_QUERY_NAMES } from "./document-path.ts";
export { checkScope, isCanonicalScope, scopeProblem } from "./scope.ts";
export { externalUrlProblem, isLoopbackHost } from "./external-url.ts";
export { PAGE_SANDBOX, PAGE_SANDBOX_FLAGS, REFUSED_SANDBOX_FLAGS, PAGE_FRAME_ALLOW, DOCUMENT_CSP, DOCUMENT_PERMISSIONS_POLICY, SHELL_PERMISSIONS_POLICY, FILE_CSP, shellCsp } from "./sandbox.ts";
export { createRateLimiter, createPageBudget, type RateLimiter, type PageBudget, type RateBudget, type BudgetRequest } from "./rate-limit.ts";
export { isOwnFilePath, ownFileReference, shellFetchLimit, isOpenableInTab, isLargeMediaType, downloadName, baseName, encodeFilePath } from "./own-files.ts";
export { quotable } from "./quotable.ts";
export * from "./capabilities/index.ts";
export { signPayload, openToken, lifetimeValid, hmacHex } from "./tokens/mac.ts";
export { mintActionToken, verifyActionToken, type ActionToken } from "./tokens/action-token.ts";
export { mintRenderToken, verifyRenderToken, type RenderToken } from "./tokens/render-token.ts";
export { mintAnswerToken, verifyAnswerToken, type AnswerToken } from "./tokens/answer-token.ts";
export { mintChallenge, openChallenge, challengeMatches, challengeId, paramsFingerprint, type ConfirmationChallenge, type ConfirmationBinding, type ChallengeKind } from "./tokens/confirmation.ts";
export { mintSelectionToken, verifySelectionToken, type SelectionToken } from "./tokens/selection-token.ts";
export { workspaceIdFor, isWorkspaceDigest } from "./tokens/workspace-id.ts";
export { parseSubmission, isSafeUploadName, shortenTranscript, TRANSCRIPT_SHORTENED, type Submission, type SubmissionFile, type Answer, type AnswerValue } from "./submissions/parse.ts";
export { formatSubmissionMessage, formatReplyMessage, formatPromptMessage, sentFromLine, EARLIER_VERSION_LINE, DEFAULT_FORM_TITLE, DEFAULT_REPLY_TITLE, type FormattedSubmission, type Framing } from "./submissions/message.ts";
export { createOutcomeMemory, idempotencyKey, type OutcomeMemory, type Remembered, type IdempotencyKey } from "./submissions/idempotency.ts";
export { boundRow, boundRows, type BoundableRow } from "./messages/bound.ts";
export { createLedger, type Ledger, type LedgerEntry, type LedgerRow } from "./messages/ledger.ts";
export { encodeCursor, decodeCursor, isCursorString } from "./messages/cursor.ts";
export type { SiteStrategy } from "./site-strategy.ts";
